- app/app.py
- app/auth.py
- app/config.schema.json
- app/utils.py
- example_config_combined.yaml
- example_config_main.yaml
- example_config_s4s.yaml
- tests/test_utils.py
restructures the config so multiple auth methods can be supported and it is easy to add more.
google_iap and no_auth are defined as the 2 supported methods now.
> restructure config to support auth methods

- .github/workflows/build.yml
let's not set this here, github will respect the version specified in `.python-version`
> build: remove hardcoded python version

- examples/scripts/example/__init__.py
- examples/scripts/example_no_access/__init__.py
- examples/scripts/kafka/kafka.py
- script_runner/__init__.py
- script_runner/app.py
- script_runner/context.py
- script_runner/utils.py
- tests/example/__init__.py
- tests/invalid_example/__init__.py
previously user scripts needed to take `config` as a first argument, and they were passed any relevant region/group specific config (for example the list of kafka brokers). now we also want to pass the `region` in. this revealed a problem with the previous api, as it was not easy to modify in a backward-compatible way. now functions take no config argument. instead they have access to a context object that contains just the region and the group config. this can also be extended in the future if we want to add properties here in a backward compatible way which requires no changes to existing functions.
> a better function api

- .gitignore
- MANIFEST.in
- pyproject.toml
- specify only the `script_runner` package to be included as we do not need the tests and examples to be there
- instead of including all frontend files by default then removing some, this only only includes the built dist files and everything else is omitted by default
- add license to package
> adjust the files in the package

- .craft.yml
it's a bit weird that the only one release on github was 0.0.1 let's keep this up to date too
> add github as release target

- script_runner/auth.py
mypy should have complained, unfortunately the lru_cache seems like it prevented that
> pass the right args to get_group_membership

- examples/scripts/kafka/kafka.py
it will throw a TypeError and fail to make any queries if we use UserDict
> fix kafka module: confluent kafka requires this to be a dict

- examples/scripts/access_logs/__init__.py
- examples/scripts/example/__init__.py
- examples/scripts/kafka/kafka.py
- script_runner/app_blueprint.py
- script_runner/function.py
- script_runner/testutils.py
script-runner only support passing args as strings. this enforces that on startup now.
> validation: check all functions have string args on startup

- examples/scripts/example/__init__.py
- script_runner/frontend/src/App.css
- script_runner/frontend/src/Chart.tsx
- script_runner/frontend/src/ScriptResult.tsx
- script_runner/frontend/src/types.tsx
the chart example previously was pretty janky, it just looked for a field called "date" and used that as the x-axis. now the user can choose which field they want to use as the axis.
also adds an example script and moves it to it's own component. this structure should make it easier to add more visualization types in future.
> improve chart

- script_runner/frontend/src/App.css
long function names were breaking the layout before, we should truncate these so they don't break across multiple lines
> fix style for long text in nav

- examples/scripts/example/README.md
- script_runner/app_blueprint.py
- script_runner/frontend/package-lock.json
- script_runner/frontend/package.json
- script_runner/frontend/src/App.css
- script_runner/frontend/src/App.tsx
- script_runner/frontend/src/Document.tsx
- script_runner/frontend/src/Nav.tsx
- script_runner/frontend/src/types.tsx
- script_runner/utils.py
we added documentation for the kafka module (https://github.com/getsentry/sentry-scripts/pull/59)
so.. may as well render it all in the UI if any markdown files are present in a group
this is what it looks like
> render documentation in the UI

- README.md
- examples/scripts/example/__init__.py
- script_runner/__init__.py
- script_runner/app_blueprint.py
- script_runner/frontend/src/Script.tsx
- script_runner/frontend/src/types.tsx
- script_runner/function.py
- script_runner/function_parameter.py
- script_runner/testutils.py
- script_runner/utils.py
- tests/example/__init__.py
- tests/test_example.py
- tests/test_utils.py
this adds the ability for users to customize the
function input types in the UI, as well as support different python types (not just strings) as arguments. now all inputs to script have to a subclass of FunctionParameter and implement its methods
this enables us to define a lot more custom behavior around the inputs. for example we can:
- have numeric types like float and int, with validation on the UI as well
- have custom input types for the same python type. e.g. now there is a regular text input as well as multi-line textarea for longer inputs.
- we can add other stuff in the future such as multiple select and custom autocompletes
> custom function parameters and input types

- script_runner/audit_log.py
- script_runner/utils.py
This adds slack event notifs for write events.
> add Slack Event notifier

- script_runner/__init__.py
- script_runner/app_blueprint.py
- script_runner/function_parameter.py
- script_runner/utils.py
- tests/test_utils.py
this is some groundwork on the api side to support autocomplete later
- adds the autocomplete input type
- adds the /autocomplete and /autocomplete_region endpoints which return the autocomplete values for all autocomplete inputs across selected regions for a given function parameter
in the future the UI will have a custom 'autocomplete' component which will call this endpoint and populate a dropdown when it sees an input with this type
> autocomplete: adding the backend type and api endpoint

- pyproject.toml
to build script runner properly we need to add the blueprint package.
> add extra package

- script_runner/blueprints/main_config_bp.py
this line was causing the proper response headers to go missing even when we get 200 responses
the `/autocomplete` endpoint could not be loaded since it was missing proper `content-type` and other headers
this wasn't noticable in dev since devserver is less strict than gunicorn
> fix empty headers in /autocomplete endpoint

- script_runner/blueprints/main_config_bp.py
- script_runner/blueprints/region_config_bp.py
remove the `@authenticate` decorator from autocomplete
this fixes a `415 (Unsupported media type)` error on the autocomplete endpoint. this occurs because the authenticate decorator only works with run / post requests. this is a GET request now (for caching reasons).
we don't really need to verify a user is in the right group to allow autocomplete or any other endpoints in this application, it's only required on run.
> fix autocomplete

- script_runner/app.py
- script_runner/blueprints/main_config_bp.py
- script_runner/blueprints/region_config_bp.py
- script_runner/config.py
- script_runner/decorators.py
previously the decorators and blueprint files were importing app.py, and app.py was also importing the decorators and blueprint files. delayed imports was being used to get around it, but this is a workaround that really shouldn't be needed.
since app.py is the top level of the flask application, no one else should be importing it.
> fix: Fix circular dependency

- script_runner/frontend/src/Script.tsx
- script_runner/frontend/src/api.tsx
if the selected region changes, we need to reload the list of autocomplete options otherwise we are showing the stale ones
if no region is selected, don't call the API, immediately return an empty autocomplete list
> autocomplete: ui improvements

- script_runner/frontend/src/App.tsx
- script_runner/frontend/src/Header.tsx
- script_runner/frontend/src/types.tsx
if the user sets the app name via config, we also use it for the html page title
also fixes the type of the `title` in config which is actually nullable
> dynamic page title

- script_runner/blueprints/main_config_bp.py
- script_runner/decorators.py
- this function isn't a decorator so it's a bit confusing that it was in the decorators.py file
- since it only exists to cache part of the `/config` api response, let's put it next to that api definition
> move the get_config function

- script_runner/frontend/src/App.css
fixes this bug where the dropdown is behind the input
- z-index should be set on the whole dropdown list not the nested anchors to actually work
> fix autocomplete z-index (for real this time)

- script_runner/frontend/src/ScriptResult.tsx
- script_runner/frontend/src/results/Chart.tsx
- script_runner/frontend/src/results/Download.tsx
- script_runner/frontend/src/results/Grid.tsx
- script_runner/frontend/src/results/Json.tsx
this is the first step to implementing a standard interface for react components that display results of script executions.
this will enable them to be customizable in the future, so users can contribute their own custom visualizations.
there are no functional changes or improvements here (that will come later) - this pr just shifts code mostly as-is from a single big ScriptResult component with lots of nested conditions to dedicated components for each visualization which all get passed the exact same props.
> split up the script result component
