app/requirements.txt

add requests package

---

.github/workflows/build-docker-image.yml
Dockerfile
pyproject.toml

also fix clickhouse-driver dependency

build docker image on pull request, only push on main

---

app/app.py
app/auth.py
app/config.schema.json
app/utils.py
example_config_combined.yaml
requirements.txt
tests/test_utils.py

- validate the jwt token 
- jwt audience code for google iap needs to be in config

auth: google iap

---

MANIFEST.in
pyproject.toml

to help fix the build issues on python -m build

Add frontend files to the manifest 

---

Dockerfile

This reverts commit a6791422ab33931fbcd96f3b9e9e63fc38a54ef6.
This is currently broken
error is `ImportError: libexpat.so.1: cannot open shared object file: No such file or directory`

Revert "dockerfile: swap gunicorn for pyuwsgi (#36)"

---

pyproject.toml
requirements.txt
script_runner/auth.py

doesn't check stuff like transitive membership

naive implementation of checking if user is in google group

---

script_runner/auth.py

fix reference to directory v1

---

.github/workflows/build.yml
MANIFEST.in

oops https://github.com/getsentry/script-runner/pull/47 broke the build
bring back graft/prune of frontend files
also run the build (but do not push) on PR so we can see if it is broken before merging

fix broken build

---

script_runner/app_blueprint.py

bad merge between https://github.com/getsentry/script-runner/pull/45 and https://github.com/getsentry/script-runner/pull/43
accidentally undid some changes when moving code to a different file

fix bad merge which broke the app

---

example_config_combined.yaml
script_runner/app_blueprint.py
script_runner/config.schema.json
script_runner/frontend/index.html
script_runner/frontend/src/App.tsx
script_runner/frontend/src/Header.tsx
script_runner/frontend/src/types.tsx
script_runner/utils.py

this lets the user configure it to whatever they want

ops script runner is probably not a good name anymore

---

Makefile
examples/scripts/access_logs/__init__.py
examples/scripts/example/__init__.py
examples/scripts/example_no_access/__init__.py
examples/scripts/kafka/__init__.py
examples/scripts/meta/__init__.py
script_runner/frontend/index.html
script_runner/frontend/src/Scripts.tsx
script_runner/frontend/src/types.tsx
script_runner/utils.py
tests/example/__init__.py
tests/invalid_example/__init__.py

now groups must have docstrings and they get displayed in the UI

add more documentation to the groups

---

script_runner/app_blueprint.py
script_runner/frontend/src/App.tsx
script_runner/frontend/src/Nav.tsx
script_runner/frontend/src/Script.tsx
script_runner/frontend/src/types.tsx

- don't show items user doesn't have access to
- if user has <= 2 groups, just keep the nav open on first page load
- clearer message if there are no groups, instead of just displaying '0'

minor ui tweaks

---

examples/scripts/access_logs/__init__.py
examples/scripts/example/__init__.py
examples/scripts/kafka/kafka.py
examples/scripts/meta/__init__.py
script_runner/testutils.py
setup.py

add an `execute_with_context` function to make it easier for user of this library to write tests against mock context

add testing utility

---

README.md
script_runner/app_blueprint.py
script_runner/frontend/src/App.css
script_runner/frontend/src/Header.tsx
script_runner/frontend/src/Nav.tsx
script_runner/frontend/src/Script.tsx
script_runner/frontend/src/Tag.css
script_runner/frontend/src/Tag.tsx
script_runner/frontend/src/api.tsx
script_runner/frontend/src/types.tsx
script_runner/frontend/vite.config.ts

Adding in a status tag to the front-end for help show the read and write aspect of each function. Also added in setup steps in the readme!

Adding in a status tag to highlight read/write functionality 

---

script_runner/app_blueprint.py
script_runner/frontend/src/Header.tsx
script_runner/frontend/src/Nav.tsx
script_runner/frontend/src/Script.tsx
script_runner/frontend/src/Tag.css
script_runner/frontend/src/Tag.tsx
script_runner/frontend/src/api.tsx
script_runner/frontend/src/types.tsx

Fixes:
- Fixing the label alignment
- Renamed type it `isReadonly` within the api
- Added the lighting bolt back
- Remove console logs

Style Cleanup

---

script_runner/frontend/src/App.css
script_runner/frontend/src/Script.tsx

now the user must click an additional checkbox to confirm they want to run a write action

add confirmation step for write actions

---

script_runner/testutils.py

now we also check that the result is json serializable and it can be returned by the api

improve testing utilities

---

script_runner/frontend/src/App.css
script_runner/frontend/src/Document.tsx

long pages were getting truncated, now we scroll

fix scrolling on docs pages

---

script_runner/frontend/src/App.css

the nav headings in the sidebar had a weird scrolling effect when collapsed, remove this

remove weird scrolling of nav headings

---

README.md
examples/scripts/example/__init__.py
script_runner/__init__.py
script_runner/app_blueprint.py
script_runner/frontend/src/App.css
script_runner/frontend/src/App.tsx
script_runner/frontend/src/Input.tsx
script_runner/frontend/src/Script.tsx
script_runner/frontend/src/api.tsx
script_runner/frontend/src/types.tsx
script_runner/function_parameter.py
tests/example/__init__.py
tests/test_utils.py

introduce an <Input /> component which supports autocompletion
there are 2 types of autocompletion types supported -  dynamic + static
- dynamic will be loaded each time based on selected regions
- static is predefined in code

autocomplete part 2: frontend component

---

script_runner/testutils.py
tests/example/__init__.py
tests/test_example.py
tests/test_utils.py

now the `execute_with_context` test utility will check a function to see if it has any `DynamicAutocomplete` parameters, and generate the autocompletions if so.
it asserts that all autocomplete functions return a list of strings, and returns the values to the user so that can make test specific assertions on them.

test utilities for autocomplete
